-- Draft schema for Guardian memory. Apply only to the selected project.
begin;

create table public.facts (
    id bigint generated by default as identity primary key,
    telegram_user_id bigint not null check (telegram_user_id > 0),
    category text not null,
    fact_text text not null check (length(trim(fact_text)) > 0),
    source text not null default 'user',
    confidence double precision not null default 1.0 check (confidence between 0 and 1),
    created_at timestamptz not null default now()
);

create table public.observations (
    id bigint generated by default as identity primary key,
    telegram_user_id bigint not null check (telegram_user_id > 0),
    category text not null,
    observation_text text not null check (length(trim(observation_text)) > 0),
    evidence text,
    confidence double precision not null default 0.5 check (confidence between 0 and 1),
    status text not null default 'active',
    created_at timestamptz not null default now()
);

create table public.goals (
    id bigint generated by default as identity primary key,
    telegram_user_id bigint not null check (telegram_user_id > 0),
    category text not null,
    goal_text text not null check (length(trim(goal_text)) > 0),
    status text not null default 'active',
    priority integer not null default 5,
    source text not null default 'user',
    created_at timestamptz not null default now()
);

create table public.events (
    id bigint generated by default as identity primary key,
    telegram_user_id bigint not null check (telegram_user_id > 0),
    category text not null,
    event_text text not null check (length(trim(event_text)) > 0),
    event_date text,
    source text not null default 'user',
    created_at timestamptz not null default now()
);

create index facts_user_id_idx on public.facts (telegram_user_id, id);
create index observations_user_active_idx on public.observations (telegram_user_id, id) where status = 'active';
create index goals_user_active_idx on public.goals (telegram_user_id, priority desc, id) where status = 'active';
create index events_user_id_idx on public.events (telegram_user_id, id);

alter table public.facts enable row level security;
alter table public.observations enable row level security;
alter table public.goals enable row level security;
alter table public.events enable row level security;

revoke all on public.facts, public.observations, public.goals, public.events from public, anon, authenticated;
revoke all on sequence public.facts_id_seq, public.observations_id_seq, public.goals_id_seq, public.events_id_seq from public, anon, authenticated;
grant select, insert on public.facts, public.observations, public.goals, public.events to service_role;
grant usage, select on sequence public.facts_id_seq, public.observations_id_seq, public.goals_id_seq, public.events_id_seq to service_role;

commit;
